### ISSUE TITLE
Unable to read secret key from file: xxx (it may not be a PGP secret key ring)

### ISSUE THREAD

**Issue by Heart-Beats** [medivh-project/medivh-publisher#2]
![image](https://github.com/user-attachments/assets/d43d8574-24ef-4fbc-8529-2df4e88e2a70)

这个问题我在使用 maven-publish 插件时就遇到了这个问题，因为 medivh-Publisher 对文件签名这块没有改动，还是使用之前的那套所以出问题也并不奇怪，问题的原因我也搜索过：
![image](https://github.com/user-attachments/assets/4dd5c851-676a-4ac2-86c3-258cf9422eb0)

这里贴下我的解决方法：
```groovy
apply plugin: 'tech.medivh.plugin.publisher'
apply plugin: 'signing'
signing {
  useGpgCmd() //使用 gpg-agent
}

medivhPublisher {
  // ...
}
```
如上就是重新引入 sign 插件，修改签名时的配置，因此 MedivhPublisherExtension  这个配置中最好添加支持 sign 的配置，不然按上面的修改还是很丑陋的，希望可以采纳尽快修改，该插件我觉得将组件由 maven 中央仓库从  Ossrh 迁移到 MavenCentral  Portal 还是很方便友好的。

**Comment by gongxuanzhang** [comment]
move to https://github.com/medivh-project/medivh-publisher/issues/3 for discussion

**Comment by gongxuanzhang** [comment]
这个问题应该是没有配置signing.secretKeyRingFile导致的
可以参考一下这个文档 https://github.com/medivh-project/medivh-publisher/blob/main/doc/zh/gpg_guide.adoc#5-%E8%AE%BE%E7%BD%AE%E9%85%8D%E7%BD%AE
如果还有问题的话我们继续讨论

**Comment by gongxuanzhang** [comment]
收到

**Comment by gongxuanzhang** [comment]
此功能完成在 https://github.com/medivh-project/medivh-publisher/commit/bce4a018ae87e5c4f647376da1590f7482cbb921

更新版本

```kts
id("tech.medivh.plugin.publisher") version "1.2.1"
```

你可以直接以这种方式配置原生signing而不需要额外的import

```kts
medivhPublisher {
    signing{
        useGpgCmd()
    }
}
```

@Heart-Beats  感谢你的issue

**Comment by Heart-Beats** [comment]
> 此功能完成在 [bce4a01](https://github.com/medivh-project/medivh-publisher/commit/bce4a018ae87e5c4f647376da1590f7482cbb921)
> 
> 更新版本
> 
> ```kotlin
> id("tech.medivh.plugin.publisher") version "1.2.1"
> ```
> 
> 你可以直接以这种方式配置原生signing而不需要额外的import
> 
> ```kotlin
> medivhPublisher {
>     signing{
>         useGpgCmd()
>     }
> }
> ```
> 
> @Heart-Beats 感谢你的issue

好的，等你的最终版本我一起来测试，最近项目上事情稍微比较多
